pipeline:
  identifier: Build_harness_workshop_harness_cie_lab_1701805257767
  name: Build harness-cie-lab
  orgIdentifier: Lloyds_Workshop
  projectIdentifier: lbgrjhnmp
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.workshopgithub
        repoName: harness-workshop/harness-cie-lab
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: ls
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
